steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/maxmenu-447510/maxmenu-php-a/menu-service',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/maxmenu-447510/maxmenu-php-a/menu-service']

images:
  - 'europe-west1-docker.pkg.dev/maxmenu-447510/maxmenu-php-a/menu-service'